name: "Refresh Packages"

on:
  push:
    branches: [ main ]
    paths:
      - 'debs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dpkg-dev
        run: sudo apt-get install -y dpkg-dev

      - name: Generate Packages
        run: |
          rm -rf Packages Packages.gz
          dpkg-scanpackages --arch arm64 debs > Packages
          gzip -9c Packages > Packages.gz

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: .
          clean: false
